[font]
size = 12.0

[font.bold]
family = "JetBrainsMonoNerdFont"
style = "Bold"

[font.italic]
family = "JetBrainsMonoNerdFont"
style = "Italic"

[font.normal]
family = "JetBrainsMonoNerdFont"
style = "Regular"

[window]
opacity = 0.01
dynamic_padding = true
decorations = "None"

[window.padding]
x=1
y=1

[colors.primary]
foreground = "#d8cab8"
background = "#141216"

[colors.cursor]
text = "#c8cab8"
cursor =  "#ac82e9"

[cursor]
style = {shape="Beam",blinking="On"}

[colors.normal]
black = "#2b2135"
# red = "#fc4649"
red = "#fc5f62" # lightened the red slightly
green = "#c4e881"
yellow = "#f3fc7b"
blue = "#7b91fc"
magenta = "#fc92fc"
cyan = "#92fcfa"
white = "#d8cab8"

[colors.bright]
black = "#2b2135"
# red = "#fc4649"
red = "#fc5f62"
green = "#c4e881"
yellow = "#f3fc7b"
blue = "#7b91fc"
magenta = "#fc92fc"
cyan = "#92fcfa"
white = "#d8cab8"

