# Wallpaper setup!
# To reload when you update config: Run `killall hyprpaper` and then `hyprpaper & disown`

# run `hyprctl monitors all` to see all your monitors!!! In order to create your setup.

preload = /home/froemich/Pictures/wallpaper.png

wallpaper = HDMI-A-1,/home/froemich/Pictures/wallpaper.png
